spring:
  profiles:
    active: prod

---
server:
  port: 18082

spring:
  profiles: dev
  datasource:
    activiti:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 10000
        #      auto-commit: false
        maximum-pool-size: 5
        connection-init-sql: select 1
    ssm:
      jdbcUrl: jdbc:mysql://127.0.0.1:3306/ssm?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 10000
        #      auto-commit: false
        maximum-pool-size: 5
        connection-init-sql: select 1

  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: "true" #自动更新数据库结构
  #    processes-definition-location-prefix: #流程定义文件路径 默认 classpath:/processes/
  #    processes-definition-location-suffixes: #流程文件后缀
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      naming:
        # 默认使用的命名策略是下划线分隔 ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 2
    password: root

---
server:
  port: 18082

spring:
  profiles: prod
  datasource:
    activiti:
      jdbcUrl: jdbc:mysql://139.199.179.164:3306/activiti?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 10000
        #      auto-commit: false
        maximum-pool-size: 5
        connection-init-sql: select 1
    ssm:
      jdbcUrl: jdbc:mysql://139.199.179.164:3306/ssm?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
      type: com.zaxxer.hikari.HikariDataSource
      driverClassName: com.mysql.jdbc.Driver
      hikari:
        idle-timeout: 10000
        #      auto-commit: false
        maximum-pool-size: 5
        connection-init-sql: select 1

  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: "true" #自动更新数据库结构
  #    processes-definition-location-prefix: #流程定义文件路径 默认 classpath:/processes/
  #    processes-definition-location-suffixes: #流程文件后缀
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      naming:
        # 默认使用的命名策略是下划线分隔 ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true

  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0
    timeout: 5000
    database: 2
    password: root