spring:
  profiles:
    active: prod

---
server:
  port: 18082

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000
      #      auto-commit: false
      maximum-pool-size: 20
      connection-init-sql: select 1
  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: "true" #自动更新数据库结构
  #    processes-definition-location-prefix: #流程定义文件路径 默认 classpath:/processes/
  #    processes-definition-location-suffixes: #流程文件后缀
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      naming:
        # 默认使用的命名策略是下划线分隔 ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

---
server:
  port: 18082

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://139.199.179.164:3306/activiti?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      idle-timeout: 10000
      #      auto-commit: false
      maximum-pool-size: 20
      connection-init-sql: select 1
  activiti:
    check-process-definitions: false #自动检查、部署流程定义文件
    database-schema-update: "true" #自动更新数据库结构
  #    processes-definition-location-prefix: #流程定义文件路径 默认 classpath:/processes/
  #    processes-definition-location-suffixes: #流程文件后缀
  thymeleaf:
    prefix: classpath:/static/
  jpa:
    show-sql: true
    hibernate:
      naming:
        # 默认使用的命名策略是下划线分隔 ImprovedNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl