server:
  port: 18082

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/activiti?characterEncoding=utf8&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
  activiti:
    check-process-definitions: false

mybatis:
  mapper-locations: classpath*:com.example.mapper.activiti/*.xml
  type-aliases-package: com.example.model.activiti
